### PR TITLE
Fix inactive airline foreground color

### PR DESCRIPTION
**Pull request by jclsn**
Previously the fonts were unreadable. This commit changes them to a lighter color that is already part of the palette.

### CODE REVIEW

**Comment by jclsn** [comment]
Before:
grafik

After:
grafik

**Comment by jinh0** [comment]
Hi! Thanks for the contribution! Spaceduck doesn't get enough love nowadays. Have you checked out the `dev` branch? I think I had a similar issue a while back with airline and I fixed it on that branch. As an FYI, the `dev` branch is way ahead of the `main` branch.

**Comment by jclsn** [comment]
@jinh0 Why do you have a dev branch for a colortheme? xD 

...okay, now I see why. You guys have inserted colors for all themes etc. Anyway, I am getting some errors on this branch. Is this Neovim-specific?

```vim
Error detected while processing /home/user/.vimrc[7]../home/user/.vim/plugged/spaceduck/colors/spaceduck.vim:
line  214:
E716: Key not present in Dictionary: "fg"
E116: Invalid arguments for function <SNR>51_hi
line  233:
E716: Key not present in Dictionary: "fg"
E116: Invalid arguments for function <SNR>51_hi
line  238:
E716: Key not present in Dictionary: "fg"
E116: Invalid arguments for function <SNR>51_hi
line  240:
E716: Key not present in Dictionary: "bg"
E116: Invalid arguments for function <SNR>51_hi
line  241:
E716: Key not present in Dictionary: "bg"
E116: Invalid arguments for function <SNR>51_hi
line  247:
E716: Key not present in Dictionary: "bg"
E116: Invalid arguments for function <SNR>51_hi
line  248:
E716: Key not present in Dictionary: "bg"
E116: Invalid arguments for function <SNR>51_hi
line  249:
E716: Key not present in Dictionary: "bg"
E116: Invalid arguments for function <SNR>51_hi
```

Ah okay, I inserted 

```vim
diff --git a/colors/spaceduck.vim b/colors/spaceduck.vim
index 1808ab4..15fdb3a 100644
--- a/colors/spaceduck.vim
+++ b/colors/spaceduck.vim
@@ -211,6 +211,10 @@ endif
 " }}}

 " Syntax Highlighting {{{
+"
+let s:palette.fg = s:palette.foreground
+let s:palette.bg = s:palette.background
+
 call s:hi('Normal',           s:palette.fg,          s:palette.bg                     )
 call s:hi('ColorColumn',      s:palette.none,        s:palette.cursor                 )
 call s:hi('CursorLine',       s:palette.none,        s:palette.cursor                 )
```

and now it works well. Very nice looking!

**Comment by pineapplegiant** [comment]
> @jinh0 Why do you have a dev branch for a colortheme? xD

Lol because people are hella picky about their color themes 😭

**Comment by jclsn** [comment]
@pineapplegiant I have never seen anyone take it as far as you have though. Maybe the Dracula team

**Comment by pineapplegiant** [comment]
> @pineapplegiant I have never seen anyone take it as far as you have though. Maybe the Dracula team

Ehh, I can see how you see it that way. Open source is hard & color themes are _very_ subjective.

I haven't used vim and airline in awhile so it's been especially hard to test which is why we have a dev branch. 

I also created spaceduck when I used iTerm exclusively–which I learned had been artificially  increasing the contrast in my terminal so my experience was different than others. So I _still_ need to revisit all of the colors which is why we had the dev branch lol

I'll see if I can get some love to Spaceduck this weekend. I miss arguing with @jinh0 about which shade of purple to use.

**Comment by jclsn** [comment]
This is fixed by the dev branch already.

**Pull request closed without merging**
